# Made by Puyodead1
settings:
  crystal:
    material: NETHER_STAR
    display name: "&6Enchantment Crystal &8[&7%CRYSTAL_TYPE%&8]"
    lore:
      - "&7Level: %CRYSTAL_LEVEL%"
      - "&7Right click on an item to apply."

messages:
  already enchanted: "&cThat item already contains this enchant!"
  success: "&aSuccessfully applied &e%CRYSTAL_TYPE% %CRYSTAL_LEVEL% &ato &e%ITEM_TYPE%&a!"
  invalid item: "&cThat enchant cannot be added to this item!"
  invalid player: "&cInvalid player specified!"
  invalid enchantment: "&cInvalid Enchantment! Check &e/gc enchants &cfor a list of valid enchantments."
  no permission: "&cYou do not have permission to run that command!"
  crystal given: "&aAdded &ex%CRYSTAL_AMOUNT% %DISPLAY_NAME% &ato your inventory!"
  crystal given to player: "&a%PLAYER_NAME% has been given &ex%CRYSTAL_AMOUNT% %DISPLAY_NAME%&a!"
  crystal received: "&aYou have been given &ex%CRYSTAL_AMOUNT% %DISPLAY_NAME% &afrom &e%PLAYER_NAME%&a!"
  creative error: "&cYou cannot apply crystals in creative mode!"