name: EnchantCrystals
version: ${project.version}
main: me.puyodead.enchantcrystals.EnchantCrystals
authors: [Puyodead1]
commands:
  givecrystal:
    description: Give a crystal
    aliases: [gc]
    usage: /gc <enchant name> [amount] [level] [player]
