name: EnchantCrystals
version: ${project.version}
main: me.puyodead.enchantcrystals.EnchantCrystals
author: Puyodead1
api-version: 1.13
commands:
  enchantcrystals:
    description: Give a crystal
    aliases: [ ecr ]
    usage: /ecr [enchants|give|add] <enchant name> [level] [amount] [player]
