name: EnchantCrystals
version: ${project.version}
main: me.puyodead.enchantcrystals.EnchantCrystals
author: Puyodead1
api-version: 1.13
commands:
  givecrystal:
    description: Give a crystal
    aliases: [gc]
    usage: /gc <enchant name> [amount] [level] [player]
